### ISSUE TITLE
TypeError:

### ISSUE THREAD

**Issue by LucasSpider** [geekjuruo/LEAD#2]
The code “from reader.BasicReaderWithDict import BasicReader” in file WordDictReader.py reported an error. The error was that I could not find the “.BasicReaderWithDict”. After I changed it to “from reader import BasicReader”, I reported an error “File "/home/nlp/MyProject/LEAD/LEAD-main/LEAD-main/reader/HybridReader.py", line 6, in <module>
    from reader.WordDictReader import WordDictReader
  File "/home/nlp/MyProject/LEAD/LEAD-main/LEAD-main/reader/WordDictReader.py", line 15, in <module>
    class WordDictReader(BasicReader):
TypeError: module() takes at most 2 arguments (3 given)” again. May I ask why? How to solve it.

**Comment by masr2000** [comment]
Thank you for your attention to our work. This bug is fixed.
