### ISSUE TITLE
GCC模型参数不匹配

### ISSUE THREAD

**Issue by FF202109** [geekjuruo/LEAD#6]
Download the glyph-enhanced pretrained model from [GCC](https://github.com/lbe0613/GCC) and put the model files in resources/glyph
从该网址下载的pytorch_model.bin文件会报错模型参数不匹配，忽略该错误后，纠错出来的结果会出现很多unk，效果很差，是否有其他可替换该模型参数的其他下载网址

**Comment by masr2000** [comment]
模型参数不匹配错误的具体信息是什么？如需帮助排查问题请提供详细完整的运行流程和报错信息。

**Comment by FF202109** [comment]
具体报错为：RuntimeError: Error(s) in loading state dict for GlyphEncoder:
size mismatch for bertembeddings.word embeddings.weight: copying a paramwith shape torch.Size([1176, 768]) from checkpoint, the shape incurrent modelis torch.Size([21128 768]).
size mismatch for clspredictions.bias: copying a param withshape torch.Size([1176]) from checkpoint,the shape in currentmodel is torch.Size([211281).
size mismatch for clspredictions.decoder.weight: copying aparam with shape torch.Size([1176,768]) from checkpoint theshape in current model is torch.Size([21128768]).
size mismatch for cls.predictions.decoder.bias: copying aparam with shape torch.Size([1176]) from checkpoint the shapein current model is torchSize([21128]).

**Comment by FF202109** [comment]
加入如下代码，模型可顺利运行，但是纠错的效果很差。
checkpointpop("bertembeddings.word embeddingsweight"）
checkpointpop("clspredictions.bias")
checkpoint.pop("clspredictions.decoder.weight")
checkpoint.pop("clspredictions.decoder.bias")

**Comment by zhengkunxiong** [comment]
> 加入如下代码，模型可顺利运行，但是纠错的效果很差。 checkpointpop("bertembeddings.word embeddingsweight"） checkpointpop("clspredictions.bias") checkpoint.pop("clspredictions.decoder.weight") checkpoint.pop("clspredictions.decoder.bias")

你解决了吗，gcc模型网址提供了两个模型，分别是pytorch_model和sp_model。后者才是在字形数据集上面进行微调的模型。也许应该使用后者？即使它的名字不是pytorch_model.

**Comment by zhengkunxiong** [comment]
> 加入如下代码，模型可顺利运行，但是纠错的效果很差。 checkpointpop（“bertembeddings.word embeddingsweight”） checkpointpop（“clspredictions.bias”） checkpoint.pop（“clspredictions.decoder.weight”） checkpoint.pop（“clspredictions.decoder.bias”）
我也遇见了这个问题，这个问题大概是gcc仓库里的config文件中的  "vocab_size"不正确导致的。因为实际上gcc的词表输入的是汉字中的义素。词表的大小为1076。而不是2w、3w之类的数。
至于你把这些embeddingsweight删掉，模型就会随机化这些参数。那么肯定效果很差。

**Comment by masr2000** [comment]
GCC模型是基于笔画编码的，其词表大小和正常BERT模型词表大小不一致。有两种解决方法：

1. 修改预训练模型文件夹中的`config.json`文件，其中的`vocab_size`参数修改为1176。（我之前的做法）
2. 修改代码，先使用`transformers.AutoConfig`加载配置文件，将`config.vocab_size`设置为1176，再使用该`config`加载模型文件。
